accounts/urls.py
from django.urls import path
from . import views

app_name='account'

urlpatterns = [
    path('',views.user_login,name='user_login'),
    path('sign_up', views.sign_up, name='sign_up'),
    path('otp_func', views.otp_func, name='otp_func'),
    path('new_otp',views.new_otp, name='new_otp'),
    path('user_logout', views.user_logout, name='user_logout'),
    path('forgot_password', views.forgot_password, name='forgot_password'),
    path('reset_password_validate/<uidb64>/<token>/', views.reset_password_validate, name='reset_password_validate'),
    path('reset_password', views.reset_password, name='reset_password'),
    path('profile', views.profile, name='profile'),
    path('edit_profile', views.edit_profile, name='edit_profile'),
    path('address', views.address, name='address'),
    path('add_address', views.add_address, name='add_address'),
    path('edit_address', views.edit_address, name='edit_address'),
    path('delete_address/<int:id>/', views.delete_address, name='delete_address'),
    path('change_password', views.change_password, name='change_password'),

]

coupon/urls.py
from django.urls import path
from . import views


# Create your views here.

app_name='coupon_app'   

urlpatterns = [
    path('coupon', views.coupon, name='coupon'),
]

home/urls.py
from django.urls import path
from . import views


app_name='home_app'   

urlpatterns = [
    path('',views.home,name='home'),
    
  

   
]
    

orders/urls.py
from django.urls import path
from . import views


app_name='order_app'   

urlpatterns = [
    
    path('place_order/',views.place_order,name='place_order'),
    path('cash_on_delivery/<int:number>', views.cash_on_delivery, name="cash_on_delivery"),
    path('apply_coupon/',views.apply_coupon,name='apply_coupon'),
    path('payments/',views.payments,name='payments'),
    path('order_complete/',views.order_complete,name='order_complete'),
    path('wallet_payment/<int:number>',views.wallet_payment,name='wallet_payment'),
    path('success/',views.success,name='success'),
    
    
    
    # path("payment_status/", views.payment_status, name="payment_status"),
  
    
    
   
]
    

purpleshop/urls.py
from django.conf import settings
from django.contrib import admin
from django.conf.urls.static import static
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('adminpanel/', include('adminpanel.urls')),
    path('products/', include('products.urls')),
    path('outgoing/', include('outgoing.urls')),
    path('accounts/', include('accounts.urls')),

    # ORDERS
    path('orders/', include('orders.urls')),
    
    
    # USERS
    path('users/', include('users.urls')),
    
    
    # COUPONS
    path('coupon/', include('coupon.urls')),
    
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)




# if settings.DEBUG:
#     urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import path
from . import views


app_name='user_app'   

urlpatterns = [
    path('user_order/', views.UserOrderView.as_view(), name='user_order'),
    path('invoice/<int:id>/',views.Invoice.as_view(),name="invoice"),
    path('order_track/<int:id>',views.OrderTrackView.as_view(),name='order_track'),
    
    path("cancel_order/<int:id>/", views.CancelOrder.as_view(), name="cancel_order"),
   
    path('wallet/',views.wallet,name='wallet')
  

   
]
    

users/models.py
from django.db import models

# Create your models here.

users/views.py
from django.http import HttpResponseRedirect
from django.utils import timezone
from django.shortcuts import get_object_or_404, redirect, render
from django.views import View
from django.contrib import messages

from outgoing.models import CartItem
from accounts.models import PaymentWallet, User_Profile
from orders.models import Order, OrderProduct


# Create your views here.




class UserOrderView(View):
    template_name = "user_order.html"

    def get(self, request):
        user_profile = get_object_or_404(User_Profile, user=request.user)
        orders = Order.objects.filter(user=user_profile.user, is_ordered=True).order_by("-created_at")
        user_profile_image_url = user_profile.image.url if user_profile.image else None
        

        order_data = []  # List to store order details and associated products
        
        for order in orders:
            order_products = OrderProduct.objects.filter(order=order, user=user_profile).order_by("-id")
            
            sub_total = 0
            for order_product in order_products:
                product_total = order_product.price * order_product.quantity
                sub_total += product_total
                tax = (2 * sub_total) / 100
                
                coupon_discount = order.coupon.discount_price if order.coupon else 0
                
            additional_charges = 40 + tax
            grand_total = sub_total + additional_charges-coupon_discount
            
            order_data.append({
                'order': order,
                'order_products': order_products,
                'sub_total': sub_total,
                'grand_total': grand_total,
                'user_profile':user_profile,
                'user_profile_image_url':user_profile_image_url,
                'order_id': order.id,  # Ensure that you have the correct attribute for the order ID
            })

        context = {
            
            "order_data": order_data,
            'user_profile': user_profile,
            'user_profile_image_url': user_profile_image_url
        }

        return render(request, self.template_name, context)
    
    
    
    

class OrderTrackView(View):
    template_name = "order_track.html"

    def get(self, request, id):
        order_detail = get_object_or_404(OrderProduct, id=id)
        
        
        orderstatus = order_detail.order.status
       
        accepted_timestamp = order_detail.updated_at if order_detail.updated_at else order_detail.created_at
        
        seven_days_ago = accepted_timestamp + timezone.timedelta(days=7)
        
        time = timezone.now()
        context = {
            "order_detail": order_detail,
            "orderstatus":orderstatus,
            "seven":seven_days_ago,
            "time":time,
            }
        return render(request, self.template_name, context)




#Cancel order                 
class CancelOrder(View):
    
    template_name = 'order_track.html'

    def post(self, request, id):
     
        url = request.META.get("HTTP_REFERER")
        if request.method == 'POST':
            reason = request.POST.get('cancel_reason')
            if not reason:
                messages.error(request, "Cancel reason is required.")
                return redirect(url)

            orders = get_object_or_404(OrderProduct, id=id)
            orders.user_note = reason
            orders.status = "Cancelled"
            orders.save()

            return redirect(url)

    

    

class Invoice(View):
    template_name = "user_invoice.html"

    def get(self, request, id):
        user_profile = get_object_or_404(User_Profile, user=request.user)
        order = get_object_or_404(Order, id=id, user=user_profile.user)
     
        order_products = OrderProduct.objects.filter(order=order, user=user_profile).order_by("-id")
     
        
        subtotal = sum(order_product.price * order_product.quantity for order_product in order_products)
        tax = (2 * subtotal) / 100
        shipping = 40
        coupon_discount = order.coupon.discount_price if order.coupon else 0
        grand_total = subtotal + tax + shipping - coupon_discount

        context = {
            'order': order,
            'order_products': order_products,
            'subtotal': subtotal,
            'tax': tax,
            'shipping': shipping,
            'coupon_discount': coupon_discount,
            'grand_total': grand_total,
        }

        return render(request, self.template_name, context)

    
 



def wallet(request):
    user = request.user
    if user.is_authenticated:
        user_profile = get_object_or_404(User_Profile, user=request.user)
       
        user_profile_image_url = user_profile.image.url if user_profile.image else None
        
        wallet_history = PaymentWallet.objects.filter(user=user).order_by('-created_at')
        print(wallet_history,"wallet_history|||||||||||||||||||||||||||||")
        context={
            'user_profile': user_profile,
            'user_profile_image_url': user_profile_image_url,
            'wallet_history':wallet_history,
        }
        return render(request, "wallet.html",context)
    else:
            messages.error(request, "Please login first")
            return HttpResponseRedirect("/user_login/")

users/templates/user_order.html
{% load static %}
{% include 'shop_header.html' %}
{% block content %}



<!-- breadcrumb -->
<div class="container">
    <div class="bread-crumb flex-w p-l-25 p-r-15 p-t-30 p-lr-0-lg">
        <div class='flex-w m-t-130 w-full'>
        <a href="{% url 'home_app:home' %}" class="stext-109 cl8 hov-cl1 trans-04">
            Home
            <i class="fa fa-angle-right m-l-9 m-r-10" aria-hidden="true"></i>
        </a>

        <span class="stext-109 cl4">
            My Orders
        </span>
        </div>
    </div>
</div>
    
<!-- Shoping Cart -->
<div class="container mt-3">
<form class="bg0 p-t-75 p-b-85" action="{% url 'order_app:place_order' %}" method="POST">
    {% csrf_token %}
    

        <div class="row">

            <div class="col-md-7">
            <div class="m-l-25 m-r--38 m-lr-0-xl" style="font-family: Poppins-Medium; font-size: 13px;">

                {% for order_entry in order_data %}
                    <div class="card mb-3">
                        <div class="card-body">
                            {% for item in order_entry.order_products %}
                                <div class="row no-gutters">
                                    <div class="col-md-4" style="height:200px">
                                        <img src="{{ item.product.images.url }}" alt="Product Image" class="card-img" style="height: 200px;">
                                    </div>
                                    <div class="col-md-8" >
                                        <div class="card-body">
                                            <!-- Product details for each item go here -->
                                            <h5 class="card-title" style="font-size: 18px;">{{ item.product }}</h5>
                                            <!-- Add other product details here -->
                                            <p class="card-text">
                                                {% if item.product_variant.all %}
                                                    {% for i in item.product_variant.all %}
                                                        {% if i.variant_types == 'color' %}
                                                            {{ i.variant_types | capfirst }}: {{ i.variant_value }}<br>
                                                        {% endif %}
                                                    {% endfor %}
                                                    {% for i in item.product_variant.all %}
                                                        {% if i.variant_types == 'size' %}
                                                            {{ i.variant_types | capfirst }}: {{ i.variant_value }}<br>
                                                        {% endif %}
                                                    {% endfor %}
                                                {% endif %}
                                                Quantity: {{ item.quantity }}
                                            </p>
                                            <p class="card-text">
                                                <strong>Order Total:</strong> ${{ item.product.price }}
                                            </p>
                                            <br>
                                            <a href="{% url 'user_app:order_track' item.id %}" class="btn btn-primary" style="background-color: #222; border-color: #222;">
                                                {% if item.status != 'Cancelled' %}
                                                    Track Order
                                                {% else %}
                                                    Cancel Order
                                                {% endif %}
                                            </a>
                                        </div>
                                    </div>
                                </div>
                                <hr>  <!-- Add a horizontal line between products -->
                            {% endfor %}
                            <!-- Display common order details here -->
                            <p class="card-text">
                                <small class="text-muted">Order ID: {{ order_entry.order.order_number }}</small>
                            </p>
                            <p class="card-text">
                                <strong>Subtotal:</strong> ${{ order_entry.sub_total }}
                            </p>
                            <p class="card-text">
                                <strong>Grand Total:</strong> ${{ order_entry.grand_total }}
                            </p>
                            <a href="{% url 'user_app:invoice' order_entry.order_id %}" class="btn btn-success ml-auto" data-abc="true" style="font-family: Poppins-Regular; background-color:#28375f;">
                                <i class="fa fa-download"></i> Download Invoice
                            </a>
                            
                        </div>
                    </div>
                {% endfor %}
            
                {% if order_data|length == 0 %}
                    <div class="alert alert-info" role="alert">
                        No orders available at the moment.
                    </div>
                {% endif %}
            </div>
        </div>

           

            
        <!--  Customer Details Right starts -->
            <div class="col-sm-10 col-lg-7 col-xl-5 m-lr-auto m-b-50">
                <div class="card bor10 m-l-63 m-r-40 m-lr-0-xl p-lr-15-sm">
                    <div class="card-body p-lr-40 p-t-30 p-b-40">
                        <div class="mtext-109 cl2 p-b-30">
                            <h4>{{ user_profile.user_name }}</h4>
            
                            <div class="flex-w flex-t bor12 p-t-15 p-b-30 mx-auto">
                                <img src="{{ user_profile_image_url }}" alt="Profile Image" class="img-fluid" style="width: 120px; height: 120px; display: flex; justify-content: center; text-align: center; margin-left: 75px;">
                            </div>
                        </div>
            
                        <div class="flex-w flex-t bor12 p-t-15 p-b-30">
                            <div class="size-209">
                                <span class="mtext-110 cl2">
                                    {{ user_profile.email }}
                                    {{ user_profile.address_1 }}
                                </span>
                            </div>
                        </div>
            
                        <a href="{% url 'account:profile' %}" class="flex-c-m stext-101 cl0 size-111 bg3 bor14 p-lr-15 trans-04 pointer btn-sm" style="text-decoration: none; color: white;">
                            My Profile
                        </a>
            
                        <br>
            
                        <button class="flex-c-m stext-101 cl0 size-111 bg3 bor14 p-lr-15 trans-04 pointer btn-sm">
                            My Wishlist
                        </button>
            
                        <br>
                        <a href="{% url 'user_app:wallet' %}" class="flex-c-m stext-101 cl0 size-111 bg3 bor14 p-lr-15 trans-04 pointer btn-sm" style="text-decoration: none; color: white;">
                            My Wallet
                        </a>
                        <br>
                        <a href="{% url 'coupon_app:coupon' %}" class="flex-c-m stext-101 cl0 size-111 bg3 bor14 p-lr-15 trans-04 pointer btn-sm" style="text-decoration: none; color: white;">
                            My Coupon
                        </a>
                  
                        
                    </div>
                </div>
            </div>
        </div>
    </div>
</form>
</div>
            



{% endblock %}
{% include 'footer.html' %}

users/templates/wallet.html
{% load static %}
{% include 'shop_header.html' %}
{% block content %}


<style>
    .font-center {
        text-align: center;
        margin-bottom: 20px;
    }

    .bordered {
        border: 2px solid #ddd;
        border-radius: 10px;
        padding: 15px;
    }

    .font-color-danger {
        color: #e74c3c; /* Red color */
    }

    .table th,
    .table td {
        text-align: center;
    }

    .table-striped tbody tr:nth-of-type(odd) {
        background-color: #f9f9f9; /* Alternate row color */
    }

    /* New styles for enhanced visuals */
    .wallet-icon {
        font-size: 48px;
        color: #3498db; /* Blue color */
    }

    .wallet-heading {
        font-size: 24px;
        margin-bottom: 10px;
        color: #333; /* Dark text color */
    }

    .wallet-amount {
        font-size: 18px;
        margin-bottom: 20px;
        color: #555; /* Slightly darker text color */
    }
    @import url('https://fonts.googleapis.com/css2?family=Nunito:wght@400;600;800&display=swap');


    
    #card {
      width: 650px;
      height: 200px;
      margin: 0;
      padding: 15px;
      display: flex;
      flex-direction: row;
      align-items: center;
      background: #FFFFFF;
      border-radius: 8px;
      box-shadow: rgba(0, 0, 0, 0.1) 0px 4px 12px;
    }
    
    #avatar {
      width: 200px;
      height: 200px;
      object-fit: cover;
      border-radius: 8px;
    }
    
    #info {
      width: 100%;
      height: 100%;
      margin: 0 15px;
      display: flex;
      flex-direction: column;
    }
    
    #name {
      font-size: 24px;
      font-weight: 800;
      margin: 0;
      padding: 0;
    }
    
    #activity {
      color: #999999;
      font-size: 18px;
      font-weight: 600;
      letter-spacing: -.5px;
      margin: 0;
      padding: 0;
    }
    
    #stats {
      margin: auto 0 15px 0;
      padding: 0;
      display: flex;
      flex-direction: row;
      justify-content: space-between;
    }
    
    .stats-text {
      color: #5B5B5B;
      font-size: 18px;
      font-weight: 600;
      letter-spacing: -1px;
      margin: 0;
      padding: 0;
      display: flex;
      flex-direction: row;
      align-items: center;
    }
    
    .stats-text svg {
      fill: #5B5B5B;
      width: 20px;
      height: 20px;
    }
    
    .stats-text span {
      color: #000000;
      font-weight: 800;
      margin: 0 5px;
    }
    
    #btn {
      color: #ffff;
      font-size: 20px;
      font-weight: 600;
      text-align: center;
      width: calc(100% - 20px);
      margin: 0;
      padding: 10px;
      background: #fe4c50;
      border-radius: 8px;
      cursor: pointer;
    }
    
    #btn:hover {
      background: #fe4c50;
    }
    /* only animate if the device supports hover */
@media (hover: hover) {
  #creditcard {
    /*  set start position */
    transform: translateY(110px);
    transition: transform 0.1s ease-in-out;
    /*  set transition for mouse enter & exit */
  }

  #money {
    /*  set start position */
    transform: translateY(180px);
    transition: transform 0.1s ease-in-out;
    /*  set transition for mouse enter & exit */
  }

  button:hover #creditcard {
    transform: translateY(0px);
    transition: transform 0.2s ease-in-out;
    /*  overide transition for mouse enter */
  }

  button:hover #money {
    transform: translateY(0px);
    transition: transform 0.3s ease-in-out;
    /*  overide transition for mouse enter */
  }
}

@keyframes bounce {
  0% {
    transform: translateY(0);
  }
  50% {
    transform: translateY(-0.25rem);
  }
  100% {
    transform: translateY(0);
  }
}

.button:hover .button__text span {
  transform: translateY(-0.25rem);
  transition: transform .2s ease-in-out;
}

/* styling */

@import url("https://fonts.googleapis.com/css2?family=Lato:wght@300;400&display=swap");


.button {
  border: none;
  outline: none;
  background-color: purple;
  padding: 1rem 90px 1rem 2rem;
  position: relative;
  border-radius: 8px;
  letter-spacing: 0.7px;
  background-color: #1e1e27;
  color: #fff;
  font-size: 21px;
  font-family: "Lato", sans-serif;
  cursor: pointer;
  box-shadow: rgba(0, 9, 61, 0.2) 0px 4px 8px 0px;
}

.button:active {
  transform: translateY(1px);
}

.button__svg {
  position: absolute;
  overflow: visible;
  bottom: 6px;
  right: 0.2rem;
  height: 140%;
}
/* Existing styles remain unchanged */

@media only screen and (max-width: 768px) {
    #card {
        flex-direction: column;
        align-items: stretch;
        width: 100%;
    }

    #avatar {
        width: 100%;
        height: auto;
        border-radius: 8px;
    }

    #info {
        margin: 15px 0;
    }

    #stats {
        flex-direction: column;
        text-align: center;
    }

    .stats-text {
        margin-bottom: 10px;
    }

    #btn {
        font-size: 16px;
    }
}

</style>










<!-- breadcrumb -->
<div class="container">
    <div class="bread-crumb flex-w p-l-25 p-r-15 p-t-30 p-lr-0-lg">
        <a href="{% url 'home_app:home' %}" class="stext-109 cl8 hov-cl1 trans-04">
            Home
            <i class="fa fa-angle-right m-l-9 m-r-10" aria-hidden="true"></i>
        </a>

        <span class="stext-109 cl4">
            My Wallet
        </span>
    </div>
</div>
    
<!-- Shoping Cart -->
<div class="container mt-3">
{% comment %} <form class="bg0 p-t-75 p-b-85" action="{% url 'order_app:place_order' %}" method="POST">
    {% csrf_token %} {% endcomment %}
    

    <div class="row">

     
     
   
              <!-- Item-->
     {% if wallet_history %}         
     {% for item in wallet_history %}
     <div id="card">
         <button class="button">
             <span class="button__text">
               <span>b</span><span>u</span>y</span><span> </span><span>n</span><span>o</span><span>w</span>
             </span>
             <svg class="button__svg" role="presentational" viewBox="0 0 600 600">
               <defs>
                 <clipPath id="myClip">
                   <rect x="0" y="0" width="100%" height="50%" />
                 </clipPath>
               </defs>
               <g clip-path="url(#myClip)">
                 <g id="money">
                   <path d="M441.9,116.54h-162c-4.66,0-8.49,4.34-8.62,9.83l.85,278.17,178.37,2V126.37C450.38,120.89,446.56,116.52,441.9,116.54Z" fill="#699e64" stroke="#323c44" stroke-miterlimit="10" stroke-width="14" />
                   <path d="M424.73,165.49c-10-2.53-17.38-12-17.68-24H316.44c-.09,11.58-7,21.53-16.62,23.94-3.24.92-5.54,4.29-5.62,8.21V376.54H430.1V173.71C430.15,169.83,427.93,166.43,424.73,165.49Z" fill="#699e64" stroke="#323c44" stroke-miterlimit="10" stroke-width="14" />
                 </g>
                 <g id="creditcard">
                   <path d="M372.12,181.59H210.9c-4.64,0-8.45,4.34-8.58,9.83l.85,278.17,177.49,2V191.42C380.55,185.94,376.75,181.57,372.12,181.59Z" fill="#a76fe2" stroke="#323c44" stroke-miterlimit="10" stroke-width="14" />
                   <path d="M347.55,261.85H332.22c-3.73,0-6.76-3.58-6.76-8v-35.2c0-4.42,3-8,6.76-8h15.33c3.73,0,6.76,3.58,6.76,8v35.2C354.31,258.27,351.28,261.85,347.55,261.85Z" fill="#ffdc67" />
                   <path d="M249.73,183.76h28.85v274.8H249.73Z" fill="#323c44" />
                 </g>
               </g>
               <g id="wallet">
                 <path d="M478,288.23h-337A28.93,28.93,0,0,0,112,317.14V546.2a29,29,0,0,0,28.94,28.95H478a29,29,0,0,0,28.95-28.94h0v-229A29,29,0,0,0,478,288.23Z" fill="#a4bdc1" stroke="#323c44" stroke-miterlimit="10" stroke-width="14" />
                 <path d="M512.83,382.71H416.71a28.93,28.93,0,0,0-28.95,28.94h0V467.8a29,29,0,0,0,28.95,28.95h96.12a19.31,19.31,0,0,0,19.3-19.3V402a19.3,19.3,0,0,0-19.3-19.3Z" fill="#a4bdc1" stroke="#323c44" stroke-miterlimit="10" stroke-width="14" />
                 <path d="M451.46,435.79v7.88a14.48,14.48,0,1,1-29,0v-7.9a14.48,14.48,0,0,1,29,0Z" fill="#a4bdc1" stroke="#323c44" stroke-miterlimit="10" stroke-width="14" />
                 <path d="M147.87,541.93V320.84c-.05-13.2,8.25-21.51,21.62-24.27a42.71,42.71,0,0,1,7.14-1.32l-29.36-.63a67.77,67.77,0,0,0-9.13.45c-13.37,2.75-20.32,12.57-20.27,25.77l.38,221.24c-1.57,15.44,8.15,27.08,25.34,26.1l33-.19c-15.9,0-28.78-10.58-28.76-25.93Z" fill="#7b8f91" />
                 <path d="M148.16,343.22a6,6,0,0,0-6,6v92a6,6,0,0,0,12,0v-92A6,6,0,0,0,148.16,343.22Z" fill="#323c44" />
               </g>
           
             </svg>
           </button>    <div id="info">
           <p id="name" style="color:green;"></p>
        
           <div id="stats">
             <p class="stats-text">
        
               amount :{{item.wallet_balance}}
              
             </p>
     
             <p class="stats-text">
               <svg viewBox="0 0 24 24">
                 <path d="M5.566 4.657A4.505 4.505 0 016.75 4.5h10.5c.41 0 .806.055 1.183.157A3 3 0 0015.75 3h-7.5a3 3 0 00-2.684 1.657zM2.25 12a3 3 0 013-3h13.5a3 3 0 013 3v6a3 3 0 01-3 3H5.25a3 3 0 01-3-3v-6zM5.25 7.5c-.41 0-.806.055-1.184.157A3 3 0 016.75 6h10.5a3 3 0 012.683 1.657A4.505 4.505 0 0018.75 7.5H5.25z" />
               </svg>
               {{item.created_at}}
             
             </p>
           </div>
           <p id="activity">You can use this money to purchase products</p>
         </div>
       </div>
       <br>
    {% endfor %}
{% else %} 
    <div class="alert alert-info" role="alert" style="margin-bottom: 34rem;font-family: Poppins-Regular;">
         No transactions available.
     </div> 
   {% endif %}
        

            
        <!--  Customer Details Right starts -->
            <div class="col-sm-10 col-lg-7 col-xl-5 m-lr-auto m-b-50">
                <div class="card bor10 m-l-63 m-r-40 m-lr-0-xl p-lr-15-sm">
                    <div class="card-body p-lr-40 p-t-30 p-b-40">
                        <div class="mtext-109 cl2 p-b-30">
                            <h4>{{ user_profile.user_name }}</h4>
            
                            <div class="flex-w flex-t bor12 p-t-15 p-b-30 mx-auto">
                                <img src="{{ user_profile_image_url }}" alt="Profile Image" class="img-fluid" style="width: 120px; height: 120px; display: flex; justify-content: center; text-align: center; margin-left: 75px;">
                            </div>
                        </div>
            
                        <div class="flex-w flex-t bor12 p-t-15 p-b-30">
                            <div class="size-209">
                                <span class="mtext-110 cl2">
                                    {{ user_profile.email }}
                                    {{ user_profile.address_1 }}
                                </span>
                            </div>
                        </div>
            
                        <a href="{% url 'account:profile' %}" class="flex-c-m stext-101 cl0 size-111 bg3 bor14 p-lr-15 trans-04 pointer btn-sm" style="text-decoration: none; color: white;">
                            My Profile
                        </a>
            
                        <br>
            
                        <button class="flex-c-m stext-101 cl0 size-111 bg3 bor14 p-lr-15 trans-04 pointer btn-sm">
                            My Wishlist
                        </button>
            
                        <br>
            
                        <a href="{% url 'coupon_app:coupon' %}" class="flex-c-m stext-101 cl0 size-111 bg3 bor14 p-lr-15 trans-04 pointer btn-sm" style="text-decoration: none; color: white;">
                            My Coupon
                        </a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</form>
</div>
            



{% endblock %}
{% include 'footer.html' %}