adminpanel/urls.py
from django.urls import path
from . import views

app_name='admin_panel'    

urlpatterns = [
    
    # Admin Authentication Views
    
    
    path('',views.admin_login,name='admin_login'),
    path('admin_dashboard',views.admin_dashboard,name='admin_dashboard'),
    path('admin_logout',views.admin_logout,name='admin_logout'),
    
    
     # User Management
     
    path('user_manage/',views.user_manage,name='user_manage'),
    path('user_block/<int:user_id>/',views.user_block,name='user_block'),
    
   
      # Category Management
      
    path('category_manage/',views.category_manage,name='category_manage'),
    path('add_category/',views.add_category,name='add_category'),
    path('edit_category/',views.edit_category,name='edit_category'),
    path('delete_category/<int:category_id>/',views.delete_category,name='delete_category'),
    
    
    # Product Management
    
    path('product_manage/',views.product_manage,name='product_manage'),
    path('add_product/',views.add_product,name='add_product'),
    path('edit_product/',views.edit_product,name='edit_product'),
    path('delete_product/<int:product_id>/',views.delete_product,name='delete_product'),
    
      # Product Variant Management
    
    path('product_variant_manage/',views.product_variant_manage,name='product_variant_manage'),
    path('add_product_variant/',views.add_product_variant,name='add_product_variant'),
    path('edit_product_variant/',views.edit_product_variant,name='edit_product_variant'),
    path('delete_product_variant/<int:product_variant_id>/',views.delete_product_variant,name='delete_product_variant'),
    
    
    
    # Coupon Management
    
    path('coupon_manage/', views.coupon_manage, name='coupon_manage'),
    path("add_coupon/",views.add_coupon,name="add_coupon"),
    path("edit_coupon/<int:id>/",views.edit_coupon,name="edit_coupon"),
    path("delete_coupon/<int:id>/",views.delete_coupon,name="delete_coupon"),
    
    
    # Order Management
    
    path('order_list/',views.order_list,name='order_list'),
   
    path('order_details/<int:id>/', views.order_details, name="order_details"),
    path('cancel_product/<int:order_id>/<int:product_id>/',views.cancel_product,name='cancel_product'),
    path('cancel_list/',views.cancel_list,name='cancel_list'),
    path('refund/<int:id>/',views.refund,name='refund'),
    
    # Sales Details
    path('sales_report/',views.sales_report,name='sales_report'),
    path('generate_report/',views.generate_report,name='generate_report'),
    path('sales_report_pdf/',views.sales_report_pdf,name='sales_report_pdf'),
    
 
]

home/urls.py
from django.urls import path
from . import views


app_name='home_app'   

urlpatterns = [
    path('',views.home,name='home'),
    
  

   
]
    

purpleshop/urls.py
from django.conf import settings
from django.contrib import admin
from django.conf.urls.static import static
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('adminpanel/', include('adminpanel.urls')),
    path('products/', include('products.urls')),
    path('outgoing/', include('outgoing.urls')),
    path('accounts/', include('accounts.urls')),

    # ORDERS
    path('orders/', include('orders.urls')),
    
    
    # USERS
    path('users/', include('users.urls')),
    
    
    # COUPONS
    path('coupon/', include('coupon.urls')),
    
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)




# if settings.DEBUG:
#     urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

orders/models.py
from django.db import models
from django.contrib.auth.models import User
from accounts.models import  User_Profile
from products.models import Product, ProductVariant
from coupon.models import Coupon


# Create your models here.


class Payment(models.Model):
    user = models.ForeignKey(User_Profile,on_delete=models.CASCADE)
    payment_id = models.CharField(max_length=100)
    payment_method = models.CharField(max_length=100)
    amount_paid = models.CharField(max_length=100)
    status = models.CharField(max_length=100)
    created_at = models.DateTimeField(auto_now_add=True)
    
    def __str__(self):
        return self.payment_method


class Order(models.Model):
    ORDER_STATUS = (
        (1, "New"),
        (2, "Accepted"),
        (3, "Preparing"),
        (4, "On Shipping"),
        (5, "Completed"),
        (6, "Cancelled"),
        (7, "Return"),
    )
    
    user = models.ForeignKey(User, on_delete=models.SET_NULL, null=True)
    payment = models.ForeignKey(Payment, on_delete=models.SET_NULL, blank=True, null=True)
    order_number = models.CharField(max_length=20)
    user_name = models.CharField(max_length=50,)
    phone = models.CharField(max_length=15)
    email = models.EmailField(max_length=50)
    address = models.CharField(max_length=50)
    city = models.CharField(max_length=50)
    state = models.CharField(max_length=50)
    country = models.CharField(max_length=50)
    order_total = models.FloatField()
    tax = models.FloatField()
    shipping = models.FloatField(default=True)
    status = models.IntegerField(choices=ORDER_STATUS, default=1,blank=True,null=True)
    ip = models.CharField(blank=True, max_length=20)
    is_ordered = models.BooleanField(default=False)
    coupon = models.ForeignKey(Coupon, on_delete=models.SET_NULL, null=True, blank=True)
    # tracking_no = models.CharField(max_length = 150, null=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    

    def __str__(self):
        return self.user_name
    
    
    
class OrderProduct(models.Model):
    STATUS = (
        ('New' , 'New'),
        ('Accepted' , 'Accepted'),
        ('Return','Return'),
       ('Cancelled' , 'Cancelled'),
    )
    order = models.ForeignKey(Order, on_delete=models.CASCADE)
    payment = models.ForeignKey(Payment, on_delete=models.SET_NULL, blank=True, null=True) 
    user = models.ForeignKey(User_Profile, on_delete=models.CASCADE)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    product_variant = models.ManyToManyField(ProductVariant, blank=True)
    quantity = models.IntegerField()
    price = models.FloatField()
    ordered = models.BooleanField(default=False)
    status = models.CharField(max_length=10, choices = STATUS, default="New")
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    user_note = models.CharField(blank=True, max_length=100)
     
     
    def __str__(self):
        return self.product.product_name
    
    def subtotal(self):
        return self.price * self.quantity 
    

adminpanel/views.py
from decimal import Decimal
from django.contrib.auth.models import User
from django.db.models import Q
from django.contrib import messages
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import get_object_or_404, redirect, render
from django.contrib.auth import authenticate, login, logout
from django.urls import reverse
from django.utils.text import slugify
from django.contrib.auth.decorators import login_required
from django.core.mail import EmailMessage
from django.template.loader import render_to_string
from django.db.models import Count, Sum, FloatField
from django.db.models import Sum
from django.db.models.functions import Cast
from django.views import View

from reportlab.lib import colors
from reportlab.lib.pagesizes import letter
from reportlab.platypus import SimpleDocTemplate, Table, TableStyle
from django.http import HttpResponse
from django.shortcuts import render
from orders.models import Order

from products.models import Category, Product, ProductVariant
from accounts.models import Address, PaymentWallet, User_Profile
from orders.models import Order, OrderProduct, Payment
from coupon.models import Coupon


# Create your views here.




   
# Admin Dashboard---------------------------------

@login_required
def admin_dashboard(request):
    if request.user.is_authenticated and request.user.is_superuser:
        super_user = User.objects.filter(is_superuser=True).first()
        product_counts = Product.objects.count()
        user_counts = User.objects.count()
        orders_count = Order.objects.count()

        payment_counts = (
            Payment.objects.values("payment_method")
            .annotate(count=Count("payment_method"))
            .order_by("-count")
        )
        total_payment_count = payment_counts.aggregate(Sum('count'))['count__sum']

        total_transaction_count = Payment.objects.count()

        all_payments = Payment.objects.all()
        total_revenue = sum(Decimal(payment.amount_paid) for payment in all_payments)
        total_sales = Decimal('10000.00')
        revenue_percentage = (total_revenue / total_sales) * 100

        print(f'Total Revenue: {total_revenue}')
        print(f'Revenue Percentage: {revenue_percentage:.2f}%')
        print(revenue_percentage)

        category_wise_order_count = OrderProduct.objects.values('product__category__category_name').annotate(order_count=Count('id'))
        print(category_wise_order_count, "category_wise_order_count||||||||||")

        total_income = Order.objects.aggregate(total_income=Sum('order_total'))['total_income'] or 0
        total_income = round(total_income, 2)
        print(total_income)

        total_sales = Order.objects.aggregate(total_sales=Sum('order_total'))['total_sales'] or 0
        total_sales = round(total_sales, 2)
        print(total_sales)

        # Calculate total income percentage
        income_percentage = (total_income / total_sales) * 100 if total_sales > 0 else 0
        print(income_percentage)

        total_refund_amount = PaymentWallet.objects.aggregate(total_refund=Sum('wallet_balance'))['total_refund']
        total_refund_amount = total_refund_amount or Decimal('0')
        print(total_refund_amount)

        paypal_total_amount = Payment.objects.filter(
            payment_method='PayPal'
        ).annotate(
            amount_paid_float=Cast('amount_paid', FloatField())
        ).aggregate(
            total_amount=Sum('amount_paid_float')
        )['total_amount'] or 0

        print(paypal_total_amount)

        cod_total_amount = Payment.objects.filter(
            payment_method='COD'
        ).annotate(
            amount_paid_float=Cast('amount_paid', FloatField())
        ).aggregate(
            total_amount=Sum('amount_paid_float')
        )['total_amount'] or 0
        cod_total_amount_rounded = round(cod_total_amount, 2)
        print(cod_total_amount_rounded)

        context = {
            "super_user": super_user,
            "product_counts": product_counts,
            "user_counts": user_counts,
            "orders_count": orders_count,
            "total_payment_count": total_payment_count,
            "total_transaction_count": total_transaction_count,
            "revenue_percentage": revenue_percentage,
            "category_wise_order_count": category_wise_order_count,
            "total_income": total_income,
            "income_percentage": income_percentage,
            "total_refund_amount": total_refund_amount,
            "paypal_total_amount": paypal_total_amount,
            "cod_total_amount_rounded": cod_total_amount_rounded,
        }

        return render(request, 'admin_index.html', context)
    else:
        return HttpResponseRedirect('/admin_login/')
    
    
    
    
    
    
# Admin authentiction----------------------------------

def admin_login(request):
    
    if request.method == "POST":
        username = request.POST['user_name']
        password = request.POST['password']
        
        user_obj = authenticate(request, username=username, password=password)
        
        if user_obj is not None:
            if user_obj.is_superuser:
                login(request, user_obj)
                return redirect('admin_panel:admin_dashboard')
            else:
                messages.error(request, "User is not authenticated")
        else:
            messages.error(request, "Invalid credentials")

    return render(request, "admin_login.html")






# Admin logout-------------------------------------


def admin_logout(request):
    
    logout(request)
    return render(request,'admin_login.html')



# User Management---------------------------------


def user_manage(request):
    
    user = User_Profile.objects.all()
    print(user,"user")
    context = {
        'user':user
    }
    return render(request, "user_list.html",context)


def user_block(request,user_id):
    if request.user.is_superuser:
        
        #user is block
        user=User_Profile.objects.get(id = user_id)
        
        if user.is_active:
            user.is_active = False
            user.save()
        else:
            user.is_active = True
            user.save()
        return redirect('admin_panel:user_manage')
    
    return render(request, "admin_login.html")
        
    
# Category Management------------------------------


def category_manage(request):
    
    category = Category.objects.all()
    context={
        'category':category
    }
   
    return render(request, "category_list.html",context)



# Add category---------------------------------------


def add_category(request):
    if request.user.is_superuser:
        if request.method == "POST":
            category_name = request.POST.get('name')
            category_image = request.FILES.get('image')
            category_description = request.POST.get('description')
            
            
            if category_name.strip() == '':
                messages.error(request, 'field is empty!')
                return redirect('admin_panel:add_category')
        
            existing_category = Category.objects.filter(
                Q(category_name__iexact=category_name)
            ).first()

            if existing_category:
                messages.error(request, 'The entered category is already taken')
                return redirect('admin_panel:add_category')
            
            elif not category_image:
                messages.error(request, 'image is not uploaded!')
                return redirect('admin_panel:add_category')
            
            elif category_description.strip() == '':
                messages.error(request, 'description is not given!')
                return redirect('admin_panel:add_category')
            
            else:
                slug = slugify(category_name)
                new_category =  Category.objects.create(
                    category_name=category_name, 
                    category_description=category_description, 
                    category_image=category_image, 
                    slug=slug
                    )
                
                new_category.save()
                messages.success(request,"Categories are added successfully")
                return redirect('admin_panel:category_manage')
        else:
            return redirect('admin_panel:category_manage')   
        
    return render(request, "admin_login.html")




# Edit category-----------------------------------------
    
    
    
def edit_category(request):
    if request.user.is_superuser:
        if request.method == 'POST':
            category_id = request.POST.get('category_id')
            category_name = request.POST.get('edit_name')
            category_image = request.FILES.get('edit_image')
            description = request.POST.get('edit_description')
            
            
             #---validate the form data-----

            if category_name.strip() == "":
                messages.error(request,"Field is empty!")
                return redirect('admin_panel:category_manage')
            
            existing_category = Category.objects.filter(
                Q(category_name__iexact=category_name)
            ).first()

            if existing_category:
                messages.error(request, 'The entered category is already taken')
                return redirect('admin_panel:add_category')
            
            elif not category_image:
                messages.error(request, 'Image is not uploaded!')
                return redirect('admin_panel:category_manage')
            elif description.strip() == '':
                messages.error(request, 'Description is not given!')
                return redirect('admin_panel:category_manage')
    
            # Update the category instance
        
            update = get_object_or_404(Category,id=category_id)
            update.category_name = category_name
            update.category_image = category_image

adminpanel/templates/admin_alert.html
{% comment %} <style>
    .swal2-container {
        z-index: 99999; /* Adjust the value based on your needs */
        position: relative;
    }
  </style> {% endcomment %}
  
  {% if messages %}
  <script src="https://cdn.jsdelivr.net/npm/jquery@3.6.0/dist/jquery.min.js"></script>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js"></script>
  <script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>
  
  <script>
    document.addEventListener('DOMContentLoaded', function() {
      {% for message in messages %}
        {% if message.tags %}
          {% if 'error' in message.tags %}
            Swal.fire({
              icon: "error",   
              toast: true,
              position: "top-end",
              showConfirmButton: false,
              timer: 4000,
              timerProgressBar: true,
              html: '<span style="color: red;">😢</span> {{ message }}', 
              didOpen: (toast) => {
                toast.addEventListener("mouseenter", Swal.stopTimer);
                toast.addEventListener("mouseleave", Swal.resumeTimer);
              }
            });
          {% elif 'success' in message.tags %}
            Swal.fire({
              icon: "success",
              toast: true,
              position: "top-end",
              showConfirmButton: false,
              timer: 4000,
              timerProgressBar: true,
              html: '<span>👋</span> {{ message }}',
              didOpen: (toast) => {
                toast.style.zIndex = 99999;
                toast.addEventListener("mouseenter", Swal.stopTimer);
                toast.addEventListener("mouseleave", Swal.resumeTimer);
              }
            });
  
            if (window.location.pathname === '/') {
              Swal.fire({
                title: "Congratulations!",
                text: "Your registration was successful! 🎉 You've earned a special coupon. 🎁 Purchase now and enjoy the benefits!",
                icon: "success",
                showConfirmButton: false,
                footer: '<a class="btn btn-info" href="/user/coupon/">Click Now</a>',
                backdrop: `
                rgba(0,0,0,0.0)
                url("/images/nyan-cat.gif")
                left top
                no-repeat
              `
              });
            }
          {% endif %}
        {% endif %}
      {% endfor %}
    });
  </script>
  {% endif %}
  

adminpanel/templates/order_list.html
{% extends "base.html" %}
{% load static %}
{% load custom_tags %}
{% block content %}
{% include "alert.html" %}



       
  
<!-- Content wrapper -->
<div class="content-wrapper">
              <!-- Content -->
  
              <div class="container-xxl flex-grow-1 container-p-y">
                <h4 class="fw-bold py-3 mb-4"><span class="text-muted fw-light">Order Management</h4>
               <hr class="my-5" />
               
                <div class="card">
                  <h5 class="card-header">Order List</h5>
                  <div class="table-responsive text-nowrap">
                    <table class="table table-hover">
                      <thead>
                        <tr>
                          <th>Order Id</th>
                          <th>User Name</th>
                          <th>Date</th>
                          <th>Status</th>
                          
                          
                          <th>Customer Email</th>
                          <th>Ordered Product</th>
                       
                          <th>Payment Method</th>
                          <th>Total</th>
                          
                        </tr>
                      </thead>
                      <tbody class="table-border-bottom-0">
                        {% for order in order_product %}
                        {% comment %} {% if order.order.status != "Return" %} {% endcomment %}
                        {% if order.order.status != 6 and order.order.status != 7 %}
                        
                        <tr>
                          <td><i class="fab fa-react fa-lg text-info me-3"></i> <strong>{{ order.order.id }}</strong></td>
                          <td>{{ order.user.user_name}}</td>
                          <td>{{order.created_at}}</td>
                         
                          
                          <td>
                            <span class="badge badge-sm badge-dot has-bg 
                            {% if order.order.status == 1 %}bg-success
                            {% elif order.order.status == 2 %}bg-info
                            {% elif order.order.status == 3 %}bg-warning
                            {% elif order.order.status == 4 %}bg-primary
                            {% elif order.order.status == 5 %}bg-secondary
                            {% elif order.order.status == 6 %}bg-danger
                            {% else %}bg-secondary
                            {% endif %} d-none d-sm-inline-flex">
                            {{ order.order.get_status_display }}
                            </span>
                          </td>
                        
                          <td>{{order.order.email }}</td>
                          <td>
                            {% for product in order.order.orderproduct_set.all %}
                                <div>
                                    {{ product.product.product_name }}
                                    
                                </div>
                            {% endfor %}
                        </td>
                          <td>{{order.order.payment.payment_method }}</td>
                          <td>
                            {% for product in order.order.orderproduct_set.all %}
                                {{ product.subtotal }}
                                <br>
                            {% endfor %}
                        </td>
                          
                         
                          
                          <td><span class="badge bg-label-success me-1"></span>
                            <div class="dropdown">
                              <button type="button" class="btn p-0 dropdown-toggle hide-arrow" data-bs-toggle="dropdown">
                                <i class="bx bx-dots-vertical-rounded"></i>
                              </button>
                              <a href="{% url 'admin_panel:order_details' order.order.id %}">  
                              <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-eye-fill" viewBox="0 0 16 16">
                                <path d="M10.5 8a2.5 2.5 0 1 1-5 0 2.5 2.5 0 0 1 5 0"/>
                                <path d="M0 8s3-5.5 8-5.5S16 8 16 8s-3 5.5-8 5.5S0 8 0 8m8 3.5a3.5 3.5 0 1 0 0-7 3.5 3.5 0 0 0 0 7"/>
                              </svg><i class="bi bi-eye-fill"></i>
                            </a>  
                             
      
                              <div class="dropdown-menu dropdown-menu-end" style="min-width: 200px; padding: 10px;">
                                        
                                <form action="{% url 'admin_panel:order_list' %}" method="POST" >
                                    {% csrf_token %}
                        
                                    <div style="margin-bottom: 10px;">
                                        <select class="form-control" id="variant" name="orderStatus" style="width: 100%;">
                                            <option value="" disabled selected>Order Status</option>
                                            {% for order_choice in order_status %}
                                                <option value="{{ order_choice.0 }}">{{ order_choice.1 }}</option>
                                            {% endfor %}
                                        </select>
                                    </div>
                                    
                                    <input type="hidden" name="orderId" value="{{ order.order.id }}">
                                    <input type="hidden" name="variantId" value="{{ order.product.id }}">
                        
                                    <button type="submit" class="btn btn-primary" style="width: 100%;">Submit</button>
                                </form>
                              
                            </div>
                            </div>
                          </td>
                        </tr>
                      
                
                      {% endif %}
                      {% endfor %}
                      
                    </tbody>
                    </table>
                  </div>
                </div>




                
              <!--/ Hoverable Table rows -->
             </div>
              <!-- / Content -->
  
  


  


{% endblock %}       





  
  

adminpanel/templates/refund_recieved_email.html
{% autoescape off %}

Hi {{user.first_name }},
Your refund ({{wallet}}) has been successfully approved 
{% endautoescape %}

adminpanel/templates/sales_report.html
{% extends "base.html" %}
{% load static %}
{% block content %}

<style>
  body {
      font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;
      background-color: #f8f9fa;
      margin: 0;
      padding: 0;
      box-sizing: border-box;
  }

  .table-container {
      margin: 20px;
      background-color: #fff;
      border-radius: 8px;
      box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
      overflow: hidden;
  }

  .date-inputs {
      margin-bottom: 10px;
      padding: 15px;
      background-color: #b7c2d0;
      color: #fff;
      text-align: center;
      border-bottom: 2px solid #b7c2d0;
  }

  label {
      margin-right: 10px;
  }

  input[type="date"] {
      padding: 8px;
      border-radius: 5px;
      border: 1px solid #ccc;
  }

  .buttons-container {
      display: flex;
      justify-content: space-between;
      align-items: center;
      padding: 15px;
  }

  .generate-button,
  .download-button {
      padding: 10px 20px;
      border: none;
      border-radius: 5px;
      cursor: pointer;
      color: #fff;
      font-size: 14px;
      transition: background-color 0.3s ease;
  }

  .generate-button {
      background-color: #28a745;
  }
  .status-input {
      margin-top: 10px; /* Adjust the margin to position it appropriately */
  }
  .generate-button:hover {
      background-color: #218838;
  }

  .download-button {
      background-color:#fe4c50;
  }

  .download-button:hover {
      background-color: #fe4c50;
  }

  .table-responsive {
      overflow-x: auto;
  }

  table {
      width: 100%;
      border-collapse: collapse;
      margin-bottom: 20px;
  }

  th, td {
      border: 1px solid #dee2e6;
      padding: 12px;
      text-align: left;
  }

  th {
      background-color: #007bff;
      color: #fff;
  }

  tbody tr:hover {
      background-color: #f5f5f5;
  }
  .date-inputs {
      margin-bottom: 10px;
      padding: 15px;
      background-color: #b7c2d0;
      color: #fff;
      text-align: center;
      border-bottom: 2px solid #b7c2d0;
      display: flex; /* Make it a flex container */
      justify-content: space-between; /* Space between child elements */
  }

  .date-inputs label,
  .date-inputs input,
  .date-inputs select,
  .date-inputs button {
      margin-right: 10px;
  }

</style>
       
  
<!-- Content wrapper -->
<div class="content-wrapper">
              <!-- Content -->
              <form method="get" action="{% url 'admin_panel:generate_report' %}">
              <div class="container-xxl flex-grow-1 container-p-y">
                <h4 class="fw-bold py-3 mb-4"><span class="text-muted fw-light">Sales Report</h4>
                    <a href="{% url 'admin_panel:sales_report_pdf' %}" class="btn btn-secondary">Download PDF</a>
               <hr class="my-5" />


               <div class="table-container">
                <div class="date-inputs">
                    <label for="startDate">Start Date:</label>
                    <input type="date" id="startDate" name="start_date">
                    <label for="endDate">End Date:</label>
                    <input type="date" id="endDate" name="end_date">
        
                    <div class="status-input">
                        <label for="status">Status:</label>
                        <select id="status" name="status">
                            <option value="" selected>All Status</option>
                            {% for choice in order_status_choices %}
                                <option value="{{ choice.0 }}">{{ choice.1 }}</option>
                            {% endfor %}
                        </select>
                    </div>
                    
                    <button type="submit" class="generate-button">Generate Report</button>
                </div>
            </div>
               
                
                
                <!-- Hoverable Table rows -->
                <div class="card">
                  <h5 class="card-header">Sales Reprot</h5>
                  <div class="table-responsive text-nowrap">
                    <table class="table table-hover">
                      <thead>
                        <tr>
                          <th>Id</th>
                          <th>User Name</th>
                          <th>Order Number</th>
                          <th>Order Date</th>
                          <th>Status</th>
                          <th>Tax</th>
                          <th>Shipping</th>
                          <th>Grand Total</th>
                        </tr>
                      </thead>
                      <tbody class="table-border-bottom-0">
                        {% for sale in sales %}
                        <tr>
                          
                          <td>{{ sale.id }}</td>
                          <td>{{ sale.user.username }}</td>
                          <td>{{ sale.order_number }}</td>
                          <td>{{ sale.created_at }}</td>
                          <td>{{ sale.get_status_display}}</td>
                          <td>₹ {{ sale.tax }}</td>
                          <td>₹ 40</td>
                          <td>₹ {{ sale.order_total }}</td>
                        </tr>
                      {% endfor %} 
                    </tbody>
                    </table>
                  </div>
                </div>
              <!--/ Hoverable Table rows -->

              </form>
             </div>
              <!-- / Content -->

{% endblock %}     