accounts/urls.py
from django.urls import path
from . import views

app_name='account'

urlpatterns = [
    path('',views.user_login,name='user_login'),
    path('sign_up', views.sign_up, name='sign_up'),
    path('otp_func', views.otp_func, name='otp_func'),
    path('new_otp',views.new_otp, name='new_otp'),
    path('user_logout', views.user_logout, name='user_logout'),
    path('forgot_password', views.forgot_password, name='forgot_password'),
    path('reset_password_validate/<uidb64>/<token>/', views.reset_password_validate, name='reset_password_validate'),
    path('reset_password', views.reset_password, name='reset_password'),
    path('profile', views.profile, name='profile'),
    path('edit_profile', views.edit_profile, name='edit_profile'),
    path('address', views.address, name='address'),
    path('add_address', views.add_address, name='add_address'),
    path('edit_address', views.edit_address, name='edit_address'),
    path('delete_address/<int:id>/', views.delete_address, name='delete_address'),
    path('change_password', views.change_password, name='change_password'),

]

home/urls.py
from django.urls import path
from . import views


app_name='home_app'   

urlpatterns = [
    path('',views.home,name='home'),
    
  

   
]
    

outgoing/urls.py
from django.urls import path
from . import views


app_name='outgoing_app'   

urlpatterns = [

   
 # cart view-------------
    path('cart', views.cart, name='cart'),
    path('add_cart/<int:product_id>/',views.add_cart,name='add_cart'),
    path('remove_cart/<int:product_id>/<int:cart_item_id>',views.remove_cart,name='remove_cart'),
    path('remove_cart_item/<int:product_id>/<int:cart_item_id>',views.remove_cart_item,name='remove_cart_item'),


    
    path('checkout', views.checkout, name='checkout'),

]

products/urls.py
from django.urls import path
from . import views


app_name='shop_app'   

urlpatterns = [

# products view-----------

    path('',views.shop,name='shop'),
    path('category/<slug:category_slug>/', views.shop, name='products_by_category'),
    path('category/<slug:category_slug>/<slug:product_slug>', views.single_product, name='single_product'),
    path('search/',views.search,name='search'),
    path('get_product_suggestions/', views.get_product_suggestions, name='get_product_suggestions'),
    path('filter/',views.filter,name='filter'),
    path('contact/',views.contact,name='contact')
   


]
    

purpleshop/urls.py
from django.conf import settings
from django.contrib import admin
from django.conf.urls.static import static
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('adminpanel/', include('adminpanel.urls')),
    path('products/', include('products.urls')),
    path('outgoing/', include('outgoing.urls')),
    path('accounts/', include('accounts.urls')),

    # ORDERS
    path('orders/', include('orders.urls')),
    
    
    # USERS
    path('users/', include('users.urls')),
    
    
    # COUPONS
    path('coupon/', include('coupon.urls')),
    
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)




# if settings.DEBUG:
#     urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

products/models.py
from django.urls import reverse
from django.db import models
from django.utils.safestring import mark_safe

# Create your models here.

# category model---------


class Category(models.Model):
    category_name = models.CharField(max_length=50, unique=True)
    category_description = models.CharField(max_length=50, unique=True, null=True)
    slug = models.SlugField(max_length=100, unique=True)
    category_image = models.ImageField(upload_to='photos/categories', blank=True)
    
    class Meta:
        verbose_name = 'category'
        verbose_name_plural = 'categories'
        
    def get_url(self):
        return reverse('shop_app:products_by_category', args=[self.slug])
    
    def __str__(self):
        return self.category_name


  
    
# product model---------

    
class Product(models.Model):
    product_name = models.CharField(max_length=200, unique=200)
    slug = models.SlugField(max_length=200, unique=True)
    description = models.TextField(max_length=500, unique=True)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    images = models.ImageField(upload_to='photos/products',)
    stock = models.IntegerField()
    is_available = models.BooleanField(default=True)
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    created_date = models.DateTimeField(auto_now=True)
    
    
    def get_url(self):
        return reverse('shop_app:single_product', args=[self.category.slug ,self.slug])
    
    def __str__(self):
        return self.product_name
    
    
class VariantManager(models.Manager):
    def colors(self):
        return super(VariantManager, self).filter(variant_types='color', is_active= True) 
    
    def sizes(self):
        return super(VariantManager, self).filter(variant_types='size', is_active= True)  
    
variant_types_choice = (
    ('color','color'),
    ('size','size'),
)   
class ProductVariant(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    variant_types = models.CharField(max_length=100,choices = variant_types_choice)
    variant_value = models.CharField(max_length=100)
    quantity = models.IntegerField(default=1)
    is_active = models.BooleanField(default=True)
    created_at = models.DateTimeField(auto_now=True)
    
    objects = VariantManager()
    
    def __str__(self):
        return self.variant_value

products/views.py
from django.http import Http404, HttpResponse, JsonResponse
from django.shortcuts import get_object_or_404, redirect, render
from outgoing.models import Cart, CartItem
from outgoing.views import _cart_id
from .models import Category, Product
from django.db.models import Q
from django.core.paginator import EmptyPage, PageNotAnInteger, Paginator

# Create your views here.


# shop view------------------>

def shop(request, category_slug=None):
 
    categories = None
    product = None

  
    if category_slug:
        categories = get_object_or_404(Category, slug=category_slug)
        product = Product.objects.filter(category=categories)
        paginator = Paginator(product, 4)
        page = request.GET.get('page')
        paged_product = paginator.get_page(page)
    else:
        product = Product.objects.all().order_by('id')
        paginator = Paginator(product, 8)
        page = request.GET.get('page')
        paged_product = paginator.get_page(page)


    context = {
        'product': paged_product,
        'category_slug': category_slug,
        
    }
    return render(request, "shop.html", context)

# single product view------------------>



def single_product(request,category_slug,product_slug):
    try:
        single_product = Product.objects.get(category__slug=category_slug, slug=product_slug)
        
    except Exception as e:
        raise e
    context={
        
        'single_product':single_product,
        
    }
    return render(request, "single_product.html",context)
    

# search--------------------------->


def search(request):
    products = []

    if 'search_product' in request.GET:
        search_product = request.GET['search_product']
        print(search_product,"search_product")
        if search_product:
            products = Product.objects.order_by('-created_date').filter(
                Q(description__icontains=search_product) | Q(product_name__icontains=search_product)
            )
           
    context = {
        'product': products
    }
    return render(request, "shop.html", context)




from django.http import JsonResponse

def get_product_suggestions(request):
    search_query = request.GET.get('search_query', '')
    suggestions = []

    if search_query:
        products = Product.objects.filter(title__icontains=search_query)
        suggestions = [product.title for product in products]

    return JsonResponse({'suggestions': suggestions})




# search ends --------------------------->


# filter--------------------------->

def filter(request):

    price_range = request.GET.get('price_range', 'All')
    if price_range == 'All':
        products = Product.objects.filter(is_available=True).order_by('id')
    else:
        min_price, max_price = price_range.split('-')
        products = Product.objects.filter(price__range=(min_price, max_price), is_available=True).order_by('id')
        

    serialized_products = [
        {
            'product_name': product.product_name,
            'price': product.price,
            'images': product.images,
        } for product in products
    ]


    context = {'product': serialized_products}

    return render(request, 'shop.html', context)


# filter ends--------------------------->

def contact(request):
    
    return render(request, "contact.html")
    

products/templates/shop.html
{% load static %}

	

{% include 'shop_header.html' %}
{% include 'shop_content.html' %}
{% include 'footer.html' %}

products/templates/shop_content.html
{% load static %}
<!-- Product -->
<div class="bg0 p-b-140" >
    <div class="container">
        {% if 'search' in request.path %}
        <h3 class="title-page">Search Result</h3>
        <br>
        <br>
        {% else %}
       
        
        <div class="flex-w flex-sb-m p-b-52">
            <div class='flex-w m-t-140 w-full' style='justify-content: space-between;'>
                
                <div class="flex-w flex-l-m filter-tope-group m-tb-10">
                    <a class="stext-106 cl6 hov1 bor3 trans-04 m-r-32 m-tb-5 {% if not category_slug %}how-active1{% endif %}" href="{% url 'shop_app:shop' %}" data-filter="*">
                        All Products
                    </a>
                    {% for category in links %}
                        <a class="stext-106 cl6 hov1 bor3 trans-04 m-r-32 m-tb-5 {% if category_slug|lower == category.category_name|lower %}how-active1{% endif %}" href="{{ category.get_url }}">
                            {{ category.category_name }}
                        </a>
                       
                    {% endfor %}
    
                </div>
    
                <div class="flex-w flex-c-m m-tb-10" >

                    <div class="flex-c-m stext-106 cl6 size-104 bor4 pointer hov-btn3 trans-04 m-r-8 m-tb-4 js-show-filter">
						<i class="icon-filter cl2 m-r-6 fs-15 trans-04 zmdi zmdi-filter-list"></i>
						<i class="icon-close-filter cl2 m-r-6 fs-15 trans-04 zmdi zmdi-close dis-none"></i>
						 Filter
					</div>
                    <div class="flex-c-m stext-106 cl6 size-105 bor4 pointer hov-btn3 trans-04 m-tb-4 js-show-search">
                        <i class="icon-search cl2 m-r-6 fs-15 trans-04 zmdi zmdi-search"></i>
                        <i class="icon-close-search cl2 m-r-6 fs-15 trans-04 zmdi zmdi-close dis-none"></i>
                        Search
                    </div>
                </div>
                
                <!-- Search product -->
                <div class="dis-none panel-search w-full p-t-10 p-b-15">
                    <form action="{% url 'shop_app:search' %}" method="GET">
                        <div class="bor8 dis-flex p-l-15">
                            <button type="submit" class="size-113 flex-c-m fs-16 cl2 hov-cl1 trans-04">
                                <i class="zmdi zmdi-search"></i>
                            </button>
                            <input id="searchInput" class="mtext-107 cl2 size-114 plh2 p-r-15" type="text" name="search_product" placeholder="Search">
                        </div>
                    </form>
                    <ul id="suggestionList"></ul>
                </div>
                
    
                <!-- Filter -->
                <div class="dis-none panel-filter w-full p-t-10">
                    <div class="wrap-filter flex-w  w-full p-lr-40 p-t-27 p-lr-15-sm">
                        <div class="filter-col1 p-r-15 p-b-27">
                            
                        </div>
    
                        <div class="filter-col2 p-r-15 p-b-27">
                            
                        </div>
    
                        <div class="filter-col3 p-r-15 p-b-27">
                            
                        </div>
    
                        <div class="filter-col4 p-b-27">
                        
							<div class="mtext-102 cl2 p-b-15">
								Price
							</div>

							<ul>
								<li class="p-b-6">
                                    <a href="{% url 'shop_app:filter' %}" class="filter-link stext-106 trans-04 filter-link-active">
                                        All
                                    </a>
                                </li>
                                
                                <li class="p-b-6">
                                    <a href="{% url 'shop_app:filter' %}?price_range=100.00-200.00" class="filter-link stext-106 trans-04">
                                        $100.00 - $200.00
                                    </a>
                                </li>
                                
                                <li class="p-b-6">
                                    <a href="{% url 'shop_app:filter' %}?price_range=200.00-300.00" class="filter-link stext-106 trans-04">
                                        $200.00 - $300.00
                                    </a>
                                </li>
                                
                                <li class="p-b-6">
                                    <a href="{% url 'shop_app:filter' %}?price_range=300.00-400.00" class="filter-link stext-106 trans-04">
                                        $300.00 - $400.00
                                    </a>
                                </li>
                                
                                <li class="p-b-6">
                                    <a href="{% url 'shop_app:filter' %}?price_range=400.00-500.00" class="filter-link stext-106 trans-04">
                                        $400.00 - $500.00
                                    </a>
                                </li>
                                
                                <li class="p-b-6">
                                    <a href="{% url 'shop_app:filter' %}?price_range=500.00" class="filter-link stext-106 trans-04">
                                        $500.00+
                                    </a>
                                </li>
                                
							</ul>
						</div>
                    </div>
                </div>



            </div>
            
        </div>
        {% endif %}

        <div class="row isotope-grid">
            {% if product %}
            
            {% for item in product %}
           
            <div class="col-sm-6 col-md-4 col-lg-3 p-b-35 isotope-item women"  >
                <!-- Block2 -->
                <div class="block2">
                   
               <div class="block2-pic hov-img0" >
                        <a href="{{ item.get_url }}">
                            <img src="{{ item.images.url }}" alt="IMG-PRODUCT" style="height: 339px; width: 270px;">
                        </a>

                    </div> 
                   

                    <div class="block2-txt flex-w flex-t p-t-14">
                        <div class="block2-txt-child1 flex-col-l ">
                            <a href="{{ item.get_url }}" class="stext-104 cl4 hov-cl1 trans-04 js-name-b2 p-b-6">
                                {{ item.product_name }}
                            </a>

                            <span class="stext-105 cl3">
                                ${{ item.price }}
                            </span>
                        </div>
                    </div>
                </div>
            </div>
            {% endfor %}
            {% else %}
            <div style="width: 100%; text-align: center;">
                <h3 style="margin: 0 auto;">No Result Found</h3>
            </div>
            {% endif %}
            {% comment %} <div class="col-sm-6 col-md-4 col-lg-3 p-b-35 isotope-item women"> {% endcomment %}
        </div>

       
        <!-- Pagination -->
			<div class="flex-c-m flex-w w-full p-t-38">
                {% if product.has_other_pages %}
                {% if product.has_previous %}
                <a href="?page={{ product.previous_page_number }}" class="flex-c-m how-pagination1 trans-04 m-all-7 active-pagination1">
					Back
				</a>
                {% else %}
                <a href="#" class="flex-c-m how-pagination1 trans-04 m-all-7">
					Back
				</a>
                {% endif %}

                {% for i in product.paginator.page_range %}
                {% if product.number == i %}
				<a href="#" class="flex-c-m how-pagination1 trans-04 m-all-7 active-pagination1">
					{{i}}
				</a>
                {% else %}
                <a href="?page={{i}}" class="flex-c-m how-pagination1 trans-04 m-all-7">
					{{i}}
				</a>
                {% endif %}
                {% endfor %}

				{% if product.has_next %}
                <a href="?page={{ product.next_page_number }}" class="flex-c-m how-pagination1 trans-04 m-all-7 active-pagination1">
					Next
				</a>
                {% else %}
                <a href="#" class="flex-c-m how-pagination1 trans-04 m-all-7 ">
					Next
				</a>
                {% endif %}
                {% endif %}
			</div>
    </div>
</div>
    

<script>
    document.addEventListener('DOMContentLoaded', function () {
        const searchInput = document.querySelector('#searchInput');
        const suggestionList = document.querySelector('#suggestionList');
    
        searchInput.addEventListener('input', function () {
            const searchQuery = searchInput.value.trim();
    
            if (searchQuery !== '') {
                fetch(`/shop_app/get_product_suggestions/?search_query=${searchQuery}`)
                    .then(response => response.json())
                    .then(data => {
                        suggestionList.innerHTML = '';
                        data.suggestions.forEach(suggestion => {
                            const listItem = document.createElement('li');
                            listItem.textContent = suggestion;
                            suggestionList.appendChild(listItem);
                        });
                    })
                    .catch(error => console.error('Error fetching suggestions:', error));
            } else {
                suggestionList.innerHTML = '';
            }
        });
    });
</script>

products/templates/shop_header.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
	<title> {% block title %} Shop {% endblock %}</title>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
    

<!--===============================================================================================-->	
	<link rel="icon" type="image/png" href="{% static 'user\assets\images\icons\favicon.png' %}"/>
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static 'user\assets\vendor\bootstrap\css\bootstrap.min.css' %}">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static 'user\assets\fonts\font-awesome-4.7.0\css\font-awesome.min.css' %}">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static 'user\assets\fonts\iconic\css\material-design-iconic-font.min.css' %}">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static 'user\assets\fonts\linearicons-v1.0.0\icon-font.min.css' %}">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static 'user\assets\vendor\animate\animate.css' %}">
<!--===============================================================================================-->	
	<link rel="stylesheet" type="text/css" href="{% static 'user\assets\vendor\css-hamburgers\hamburgers.min.css' %}">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static 'user\assets\vendor\css-hamburgers\hamburgers.min.css' %}">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static 'user\assets\vendor\select2\select2.min.css' %}">
<!--===============================================================================================-->	
	<link rel="stylesheet" type="text/css" href="{% static 'user\assets\vendor\daterangepicker\daterangepicker.css' %}">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static 'user\assets\vendor\slick\slick.css' %}">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static 'user\assets\vendor\MagnificPopup\magnific-popup.css' %}">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static 'user\assets\vendor\perfect-scrollbar\perfect-scrollbar.css' %}">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static 'user\assets\css\util.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'user\assets\css\main.css' %}">
<!--===============================================================================================-->
    <!-- Add SweetAlert library -->
    <script src="https://cdn.jsdelivr.net/npm/sweetalert2@10"></script>
<!--===============================================================================================-->

<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" crossorigin="anonymous">

<!-- Include the PayPal JavaScript SDK -->
<script src="https://www.paypal.com/sdk/js?client-id=AepSdEgnLb5ksacJ0CoS2bG1flWKr3kQevJcP3NtsPqBr5KJgKVcJlSPpjkogITKDmpL-HHfHiHSEEQk&currency=USD"></script>

 <!-- Add these links in your HTML head section -->
{% comment %} <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css"> {% endcomment %}
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8sh+WyIo1mLx4e7xj" crossorigin="anonymous">

<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script> 




</head>
<body class="animsition">
<!-- Header -->
<header class="header-v4">
    <!-- Header desktop -->
    <div class="container-menu-desktop">
        <!-- Topbar -->
        <div class="top-bar">
            <div class="content-topbar flex-sb-m h-full container">
                <div class="left-top-bar">
                    Free shipping for standard order over $100
                </div>

                <div class="right-top-bar flex-w h-full">
                    
                    {% if user.is_authenticated %}
                    <a href="{% url 'account:profile' %}" class="flex-c-m trans-04 p-lr-25">
                        My Account
                    </a>
                    
                    
                    {% else %}
                    <a href="{% url 'account:user_login' %}" class="flex-c-m trans-04 p-lr-25">
                        Register
                    </a>
                    {% endif %}

                </div>
            </div>
        </div>

         <div class="wrap-menu-desktop how-shadow1">
            <nav class="limiter-menu-desktop container">
                
                <!-- Logo desktop -->		
                <a href="{% url 'home_app:home' %}" class="logo">
                    <img src="{% static 'user\assets\images\icons\logo-01.png' %}" alt="IMG-LOGO">
                </a> 

                <!-- Menu desktop -->
                <div class="menu-desktop">
                    <ul class="main-menu">
                        <li>
                            <a href="{% url 'home_app:home' %}">Home</a>
                           
                        </li>

                        <li>
                            <a href="{% url 'shop_app:shop' %}">Shop</a>
                        </li>

                        
                        <li>
                            <a href="{% url 'shop_app:contact' %}">Contact</a>
                        </li>
                    </ul>
                </div>	 

                <!-- Icon header -->
              <div class="wrap-icon-header flex-w flex-r-m">
                    

                        <a href="{% url 'outgoing_app:cart'%}" class="icon-header-item cl2 hov-cl1 trans-04 p-r-11 p-l-10 icon-header-noti js-show-cart" data-notify={{cart_count}}>
                            <i class="zmdi zmdi-shopping-cart"></i>
                        </a>
         

                    <a href="{% url 'outgoing_app:checkout' %}" class="icon-header-item cl2 hov-cl1 trans-04 p-l-22 p-r-11 icon-header-noti" data-notify="0">
                        <i class="zmdi zmdi-favorite-outline"></i>
                    </a>
                </div>
       </nav>
        </div>	
    </div> 

    <!-- Header Mobile -->
    <div class="wrap-header-mobile">
        <!-- Logo moblie -->		
        <div class="logo-mobile">
            <a href="{% url 'home_app:home' %}"><img src="{% static 'user\assets\images\icons\logo-01.png' %}" alt="IMG-LOGO"></a>
        </div>

        <!-- Icon header -->
        <div class="wrap-icon-header flex-w flex-r-m m-r-15">
          

            <div class="icon-header-item cl2 hov-cl1 trans-04 p-r-11 p-l-10 icon-header-noti js-show-cart" data-notify={{ cart_count }}>
                <i class="zmdi zmdi-shopping-cart"></i>
            </div>

            <a href="{% url 'outgoing_app:checkout' %}" class="dis-block icon-header-item cl2 hov-cl1 trans-04 p-r-11 p-l-10 icon-header-noti" data-notify="0">
                <i class="zmdi zmdi-favorite-outline"></i>
            </a>
        </div>

        <!-- Button show menu -->
        <div class="btn-show-menu-mobile hamburger hamburger--squeeze">
            <span class="hamburger-box">
                <span class="hamburger-inner"></span>
            </span>
        </div>
    </div>


    <!-- Menu Mobile -->
    <div class="menu-mobile">
        <ul class="topbar-mobile">
            <li>
                <div class="left-top-bar">
                    Free shipping for standard order over $100
                </div>
            </li>

            <li>
                <div class="right-top-bar flex-w h-full">
                    <a href="#" class="flex-c-m p-lr-10 trans-04">
                        Help & FAQs
                    </a>

                    {% if user.is_authenticated %}
                    <a href="{% url 'account:profile' %}" class="flex-c-m trans-04 p-lr-25">
                        My Account
                    </a>
                    {% else %}
                    <a href="{% url 'account:profile' %}" class="flex-c-m trans-04 p-lr-25">
                        Register
                    </a>
                    {% endif %}

                    
                </div>
            </li>
        </ul>

      <ul class="main-menu-m">
            <li>
                <a href="{% url 'home_app:home' %}">Home</a>
                
                <span class="arrow-main-menu-m">
                    <i class="fa fa-angle-right" aria-hidden="true"></i>
                </span>
            </li>

            <li>
                <a href="product.html">Shop</a>
            </li>
            
            

            <li>
                <a href="{% url 'shop_app:contact' %}">Contact</a>
            </li>
        </ul>
    </div> 
</header>

</body>
</html>

<script src="{% static 'user\login_assets\js\jquery.min.js' %}"></script>
    <script src="{% static 'user\login_assets\js\popper.js' %}"></script>
    <script src="{% static 'user\login_assets\js\bootstrap.min.js' %}"></script>
    <script src="{% static 'user\login_assets\js\main.js' %}"></script>
    <!-- Include Bootstrap JavaScript bundle at the end of the body -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js"></script>
    <!-- Include any other necessary JavaScript files -->