accounts/urls.py
from django.urls import path
from . import views

app_name='account'

urlpatterns = [
    path('',views.user_login,name='user_login'),
    path('sign_up', views.sign_up, name='sign_up'),
    path('otp_func', views.otp_func, name='otp_func'),
    path('new_otp',views.new_otp, name='new_otp'),
    path('user_logout', views.user_logout, name='user_logout'),
    path('forgot_password', views.forgot_password, name='forgot_password'),
    path('reset_password_validate/<uidb64>/<token>/', views.reset_password_validate, name='reset_password_validate'),
    path('reset_password', views.reset_password, name='reset_password'),
    path('profile', views.profile, name='profile'),
    path('edit_profile', views.edit_profile, name='edit_profile'),
    path('address', views.address, name='address'),
    path('add_address', views.add_address, name='add_address'),
    path('edit_address', views.edit_address, name='edit_address'),
    path('delete_address/<int:id>/', views.delete_address, name='delete_address'),
    path('change_password', views.change_password, name='change_password'),

]

coupon/urls.py
from django.urls import path
from . import views


# Create your views here.

app_name='coupon_app'   

urlpatterns = [
    path('coupon', views.coupon, name='coupon'),
]

home/urls.py
from django.urls import path
from . import views


app_name='home_app'   

urlpatterns = [
    path('',views.home,name='home'),
    
  

   
]
    

products/urls.py
from django.urls import path
from . import views


app_name='shop_app'   

urlpatterns = [

# products view-----------

    path('',views.shop,name='shop'),
    path('category/<slug:category_slug>/', views.shop, name='products_by_category'),
    path('category/<slug:category_slug>/<slug:product_slug>', views.single_product, name='single_product'),
    path('search/',views.search,name='search'),
    path('get_product_suggestions/', views.get_product_suggestions, name='get_product_suggestions'),
    path('filter/',views.filter,name='filter'),
    path('contact/',views.contact,name='contact')
   


]
    

purpleshop/urls.py
from django.conf import settings
from django.contrib import admin
from django.conf.urls.static import static
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('adminpanel/', include('adminpanel.urls')),
    path('products/', include('products.urls')),
    path('outgoing/', include('outgoing.urls')),
    path('accounts/', include('accounts.urls')),

    # ORDERS
    path('orders/', include('orders.urls')),
    
    
    # USERS
    path('users/', include('users.urls')),
    
    
    # COUPONS
    path('coupon/', include('coupon.urls')),
    
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)




# if settings.DEBUG:
#     urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import path
from . import views


app_name='user_app'   

urlpatterns = [
    path('user_order/', views.UserOrderView.as_view(), name='user_order'),
    path('invoice/<int:id>/',views.Invoice.as_view(),name="invoice"),
    path('order_track/<int:id>',views.OrderTrackView.as_view(),name='order_track'),
    
    path("cancel_order/<int:id>/", views.CancelOrder.as_view(), name="cancel_order"),
   
    path('wallet/',views.wallet,name='wallet')
  

   
]
    

accounts/models.py
from django.contrib.auth.models import User
from django.db import models
from coupon.models import Coupon



# Create your models here.

    
class User_Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    phone = models.BigIntegerField(null=True,blank=True)
    coupon = models.ForeignKey(Coupon,on_delete=models.CASCADE,null=True,blank=True)

    image = models.ImageField( upload_to='images/',blank=True,null=True)
    is_active = models.BooleanField(default=True) 
    wallet = models.DecimalField(default=0, decimal_places=2, max_digits=10,null=True,blank=True)

    def __str__(self):
        print(f"User instance: {self.user}")
        return self.user.username


    @property
    def user_name(self):
        print(f"User first_name: {self.user.first_name}")
        print(f"User last_name: {self.user.last_name}")
        return f"{self.user.first_name} {self.user.last_name}"


class Address(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    new_name = models.CharField(max_length=20)
    email = models.EmailField(max_length=50,blank=True)
    phone = models.BigIntegerField(null=True, blank=True)
    address = models.CharField(max_length=20)
    city = models.CharField(max_length=15)
    state = models.CharField(max_length=15,default=True,null=True)
    country = models.CharField(max_length=15)
    
    def __str__(self):
        return self.user.username
    
    
    
class PaymentWallet(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    payment_type = models.CharField(max_length=150, blank=True, null=True)
    wallet_balance = models.DecimalField(default=0, decimal_places=2, max_digits=10, null=True, blank=True)
    created_at = models.DateField(auto_now_add=True)

    def __str__(self):
        return f"PaymentWallet for User: {self.user}, Payment Type: {self.payment_type}, Created on: {self.created_at}"

accounts/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User

class SignUpForm(UserCreationForm):
    class Meta:
        model = User
        fields = ('first_name', 'last_name', 'username', 'email', 'password1', 'password2')

accounts/views.py
from base64 import urlsafe_b64decode
from email.message import EmailMessage
import random
from django.conf import settings
from django.http import HttpResponseRedirect
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth import authenticate, login, logout
from django.contrib import messages
from outgoing.models import Cart, CartItem
from outgoing.views import _cart_id
from django.contrib.auth.models import User
from django.views.decorators.cache import cache_control
from coupon.models import Coupon
from .models import  Address, User_Profile
from django.core.mail import send_mail
from django.contrib.auth.decorators import login_required
from accounts.forms import SignUpForm
from django.contrib.sites.shortcuts import get_current_site
from django.template.loader import render_to_string
from django.utils.http import urlsafe_base64_encode
from django.contrib.sites.shortcuts import get_current_site
from django.contrib.auth.tokens import default_token_generator
from django.utils.encoding import force_bytes, force_str
from django.core.mail import EmailMessage



# -------------------------SIGN_UP-------------------------


def sign_up(request):
    if request.method == 'POST':
        form = SignUpForm(request.POST)
        if form.is_valid():
          
            form.save()
            
            username = form.cleaned_data.get('username')
            print(username)
            password = form.cleaned_data.get('password1')
            print(password)
            email = form.cleaned_data.get('email')
            print(email)
            
            otp = str(random.randint(1000, 9999))
            print(otp)
            request.session['signup_username']=username
            request.session['signup_otp'] = otp
  
            subject = 'OTP Verification Code'
            message = f'Your OTP code for signup is: {otp}'
            from_email = settings.EMAIL_HOST_USER
            recipient_list = [email]
            
            
            
            send_mail(subject, message, from_email, recipient_list)
            
            messages.success(request, 'Your account has been created! Please enter OTP send to your mail')
            return redirect('account:otp_func')
        else:
            messages.warning(request,form.errors)
            return redirect('account:sign_up')

    return render(request, 'signup.html')

    
# -------------------------SIGN_UP ENDED-------------------------


# -------------------------GENERATE OTP----------------------------------

def otp_func(request):
    
    if request.method == 'POST':
        otp_entered = request.POST.get('otp_entered')
        otp_saved = request.session.get('signup_otp')
        
        if otp_entered == otp_saved:
            # OTP is valid; remove it from the session
            del request.session['signup_otp']

          
            username=request.session['signup_username']
            user = User.objects.get(username=username)
            user.is_active = True
            user.is_otp=True
            user.save()
            messages.success(request, "Your registration is successful. You can now log in.")           
            return redirect('account:user_login')  
        
        else:
            messages.error(request, 'Invalid OTP. Please try again.')
    return render(request,'otp.html')



def new_otp(request):
    
    username=request.session.get('signup_username')
    user = User.objects.get(username=username)
    request.session.pop('signup_otp', None)
  
    if user.email:
        otp = str(random.randint(1000, 9999))
        request.session['signup_otp'] = otp
        subject = 'Resent OTP Verification Code'
        message = f'Your resent OTP code for signup is: {otp}'
        from_email = 'purpleshop.tech@gmail.com'
        recipient_list = [user.email]

        send_mail(subject, message, from_email, recipient_list)

        messages.success(request, 'resend OTP sent successfully. Please check your email.')
    else:
        messages.warning(request, 'Failed to resend OTP. Please try again.')

    return redirect('account:otp_func')


# -------------------------GENERATE OTP ENDED-------------------------



# -------------------------USER LOGIN ---------------------------------

def user_login(request):
    
    if request.method == "POST":
        email = request.POST.get('email')
        print(email,"email")
        password = request.POST.get('password')
        print(password,"password")
        user = authenticate(request, email=email, password=password)

        
        if user is not None:
            print("not none")
            if user.email != email:
                messages.error(request, 'Invalid Credentials')
                return render(request, 'login.html')
            
            try:
                
                cart = Cart.objects.get(cart_id=_cart_id(request))
                is_cart_item_exists = CartItem.objects.filter(cart=cart).exists()
                if is_cart_item_exists:
                    cart_item = CartItem.objects.filter(cart=cart)
                    
                    #----------- product variants by cart id---------
                    product_variants = []
                    for item in cart_item:
                        variants = item.product_variant.all()
                        product_variants.append(list(variants))
                
                    #  ---------get cart_items from user to access product_variation  --------- 
                    cart_item = CartItem.objects.filter(user=user)
                    ex_var_list=[]
                    id = []
                    for item in cart_item:
                        existing_variation = item.product_variant.all()
                        ex_var_list.append(list(existing_variation))
                        id.append(item.id)
                    
                
                    for pro in product_variants:
                        if pro in ex_var_list:
                            index = ex_var_list.index(pro)
                            item_id = id[index]
                            item = CartItem.objects.get(id = item_id)
                            item.quantity += 1
                            item.user = user
                            item.save()
                        
                        else:
                            cart_item = CartItem.objects.filter(cart = cart)
                            for item in cart_item:
                                item.user = user
                                item.save()
                
                
            except Exception as e:
                print("Exception occurred:", e)
                pass
            
            if user:
                user_pro, created = User_Profile.objects.get_or_create(user=user)
                user_pro.email = email
                user_pro.user_name
                print(user_pro.email,"___________________________")
                coupon = Coupon.objects.first()
                user_pro.coupon = coupon
                user_pro.save()
                
            login(request, user)
            messages.success(request, "You are already a user,Create your profile")
             
            return redirect('account:edit_profile')
            
        else:
            messages.error(request, 'Invalid Credentials')

    return render(request, 'login.html')


# -------------------------USER LOGIN ENDED-------------------------


# -------------------------USER LOGOUT -------------------------


@cache_control(no_cache=True, no_store=True)
@login_required(login_url='/user_login/')
def user_logout(request):
    logout(request)
    return redirect('home_app:home')



# -------------------------USER LOGOUT ENDED-------------------------



# -------------------------FORGOT PASSWORD-------------------------




def forgot_password(request):
    if request.method == "POST":
        email = request.POST['email']
 

        if User.objects.filter(email=email).exists():
            user = User.objects.get(email__exact=email)
     

            current_site = get_current_site(request)
            mail_subject = "Reset Your Password"
            message = render_to_string(
                "reset_password_email.html",
                {
                    "user": user,
                    "domain": current_site.domain,
                    "uid": urlsafe_base64_encode(force_bytes(user.pk)),
                    "token": default_token_generator.make_token(user),
                },
            )

            to_email = email
            send_mail = EmailMessage(
                mail_subject,
                message,
                to=[to_email],  # 'to' argument should be passed here, not in MIMEPart
            )
            send_mail.send()

            messages.success(
                request, "Password reset email has been sent to your email address"
            )
         
            return redirect('account:user_login')
        else:
            messages.error(request, "Account does not exist")
            return redirect("account:forgot_password")

    return render(request, "forgot_password.html")





def reset_password_validate(request, uidb64, token):
    try:
        uid = urlsafe_b64decode(uidb64).decode()
        print(uid,"from reset password validator")
        user = User._default_manager.get(pk=uid)
    except (TypeError, ValueError, OverflowError, User.DoesNotExist):
        user = None

    if user is not None and default_token_generator.check_token(user, token):
  
        request.session["uid"] = uid
        messages.success(request, "please reset your password")
       
        return redirect("account:reset_password")
    else:
       
        messages.success(request, "this link has been expired!")
        return redirect("account:user_login")
    
    
    
    
    
def reset_password(request):

    if request.method == "POST":
  

accounts/templates/alert.html
{% comment %} <style>
    .swal2-container {
        z-index: 99999; /* Adjust the value based on your needs */
        position: relative;
    }
  </style> {% endcomment %}
  
  {% if messages %}
  <script src="https://cdn.jsdelivr.net/npm/jquery@3.6.0/dist/jquery.min.js"></script>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js"></script>
  <script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>
  
  <script>
    document.addEventListener('DOMContentLoaded', function() {
      {% for message in messages %}
        {% if message.tags %}
          {% if 'danger' in message.tags %}
            console.log("Error message detected");
            Swal.fire({
              icon: "error",
              toast: true,
              position: "top-end",
              showConfirmButton: false,
              timer: 4000,
              timerProgressBar: true,
              html: '<span style="color: red;">😢</span> {{ message|safe }}',
              didOpen: (toast) => {
                  toast.style.zIndex = 99999;
                  console.log("Message tags:", '{{ message.tags }}');  // Note the quotes around message.tags
                  toast.addEventListener("mouseenter", Swal.stopTimer);
                  toast.addEventListener("mouseleave", Swal.resumeTimer);
              }
          });
          {% elif 'success' in message.tags %}
            Swal.fire({
              icon: "success",
              toast: true,
              position: "top-end",
              showConfirmButton: false,
              timer: 4000,
              timerProgressBar: true,
              html: '<span>👋</span> {{ message }}',
              didOpen: (toast) => {
                toast.style.zIndex = 99999;
                toast.addEventListener("mouseenter", Swal.stopTimer);
                toast.addEventListener("mouseleave", Swal.resumeTimer);
              }
            });
  
           
          {% endif %}
        {% endif %}
      {% endfor %}
    });
  </script>
  {% endif %}
  

accounts/templates/change_password.html
{% load static %}
{% include 'alert.html' %}

<!DOCTYPE html>
<html lang="en">
  <head>
    <title></title>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />

    <link href="https://fonts.googleapis.com/css?family=Lato:300,400,700&display=swap" rel="stylesheet" />

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" />

    <link rel="stylesheet" href="{% static 'user/login_assets/css/style.css' %}" />
  </head>
  <body>
    <section class="ftco-section">
      <div class="container">
        <div class="row justify-content-center">
          <div class="col-md-6 text-center mb-5">
            <h2 class="heading-section"></h2>
          </div>
        </div>
        <div class="row justify-content-center">
          <div class="col-md-12 col-lg-10">
            <div class="wrap d-md-flex">
              <div class="img" style="background-image: url('{% static "user/login_assets/images/pic.jpg" %}');"></div>
              <div class="login-wrap p-4 p-md-5">
                <div class="d-flex">
                  <div class="w-100">
                    <h3 class="mb-4">Change Password</h3>
                  </div>
                 
                </div>
                <form action ="{% url 'account:change_password' %}" method="POST">
                  {% csrf_token %}
                  
                  <div class="form-group mb-3">
                    <label class="password label" for="name">Current Password</label>
                    <input type="password" class="form-control" placeholder="Current Password" name='current_password' required />
                    
                  </div>
                  <div class="form-group mb-3">
                    <label class="password label" for="name">Create New Password</label>
                    <input type="password" class="form-control" placeholder="New Password" name='new_password' required />
                  </div>
                  <div class="form-group mb-3">
                    <label class="label" for="password">Confirm New Password</label>
                    <input type="password" class="form-control" placeholder="Confirm Password" name='confirm_password' required />
                  </div>
                  <div class="form-group">
                    <button type="submit" class="form-control btn btn-primary rounded submit px-3" style="background-color:#7b5f4c;">Change Password</button>
                  </div>
                </form>
                
              </div>
            </div>
          </div>
        </div>
      </div>
    </section>

    <script src="{% static 'user\login_assets\js\jquery.min.js' %}"></script>
    <script src="{% static 'user\login_assets\js\popper.js' %}"></script>
    <script src="{% static 'user\login_assets\js\bootstrap.min.js' %}"></script>
    <script src="{% static 'user\login_assets\js\main.js' %}"></script>
  </body>
</html>

accounts/templates/otp.html
{% include 'alert.html' %} 

<!DOCTYPE html>
<html>

<head>
    <title>OTP Verification</title>
    <style>
        body {
            font-family: 'Arial', sans-serif;
            background-color: #f4f4f4;
            margin: 0;
            padding: 0;
            display: flex;
            justify-content: center;
            align-items: center;
            height: 100vh;
        }

        h1 {
            text-align: center;
            color: #333;
        }

        form {
            background-color: #fff;
            padding: 20px;
            border-radius: 8px;
            box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
        }

        label {
            display: block;
            margin-bottom: 10px;
            color: #555;
        }

        input {
            width: 100%;
            padding: 10px;
            margin-bottom: 20px;
            border: 1px solid #ccc;
            border-radius: 4px;
            box-sizing: border-box;
        }

        button {
            background-color: #007bff;
            color: #fff;
            padding: 10px 20px;
            border: none;
            border-radius: 4px;
            cursor: pointer;
        }

        button:hover {
            background-color: #0056b3;
        }

        .alert {
            margin-top: 20px;
            padding: 10px;
            color: #721c24;
            background-color: #f8d7da;
            border: 1px solid #f5c6cb;
            border-radius: 4px;
        }
    </style>
</head>

<body>
    

    <form method="POST" action="{% url 'account:otp_func' %}"> 
        {% csrf_token %}

        <label for="otp">Enter the OTP sent to your email:</label>
        <input type="text" id="otp_entered" name="otp_entered" required>

        <!--  existing timer and Resend OTP link -->
        <div class="main" style="text-align: center;">
            <p id="timer" style="font-size: 16px; color: #555; padding: 10px; border: 1px solid #ccc; background-color: #f4f4f4;margin-top: 16px;">Time left: <span id="countdown">60</span> seconds</p>
            <a href="{% url 'account:new_otp' %}" id="resendLink" style="display: none;">Resend OTP</a>
        </div>
        <button type="submit" style="background-color: black;">Verify OTP</button>
    </form>
    <script>
        var countdown = 60;
    
        function startTimer() {
            var timerInterval = setInterval(function () {
                countdown--;
                document.getElementById("countdown").innerText = countdown;
    
                if (countdown <= 0) {
                    clearInterval(timerInterval);
                    document.getElementById("timer").innerText = "Time's up!";
                    document.getElementById("resendLink").style.display = "inline"; // Show Resend OTP link
                }
            }, 1000);
        }
    
       
    
        document.addEventListener("DOMContentLoaded", function () {
            startTimer();
        });
    </script>
</body>


</html>

accounts/templates/profile.html
{% load static %}
{% include 'shop_header.html' %}
{% block content %}

<!-- breadcrumb -->
<div class="container ">
    <div class="bread-crumb flex-w p-l-25 p-r-15 p-t-30 p-lr-0-lg ">
      <div class='flex-w m-t-130 w-full' >
      <a href="index.html" class="stext-109 cl8 hov-cl1 trans-04">
        Home
        <i class="fa fa-angle-right m-l-9 m-r-10" aria-hidden="true"></i>
      </a>
      <span class="stext-109 cl4">Profile</span>
    </div>
    </div>
  </div>
<div style="text-align: center; margin-top: 20px;">
    <span class="block1-name ltext-102 trans-04 p-b-8">
        PROFILE
    </span>
</div>
<!-- Profile -->
<form class="bg0 p-t-75 p-b-0">
    <div class="container">
        <div class="row">
            <div class="col-lg-10 col-xl-7 m-lr-auto m-b-50">
                <div class="m-l-25 m-r--38 m-lr-0-xl">
                    <div class="wrap-table-shopping-cart">
                        <table class="table-shopping-cart" style="min-width: 645px;">
                            <tr class="table_row">
                                <td class="column-1">
                                    

                                    <div class="col-lg-10">
                                
                                        <div class="flex-w flex-t bor12 p-t-15 p-b-30 mx-auto ">
                                            <img src="{{ user_profile_image_url }}" alt="Profile Image" class="img-fluid" style="width: 135px; height: 135px; display: flex; justify-content: center;
                                            text-align: center;margin-left: 197px;">
                                        </div>
                                           
                                            <br>
                                            <div class="form-group row">
                                                <label for="username" class="col-sm-4 col-form-label">Full Name:</label>
                                                <div class="col-sm-8">
                                                    <div  class="form-control" id="username" name="username" readonly style="color: black; background-color: #ffffff; pointer-events: none;">
                                                    {{ user_pro.user_name }}</div>
                                                </div>
                                            </div> 
                                            <div class="form-group row">
                                                <label for="phone" class="col-sm-4 col-form-label">Phone:</label>
                                                <div class="col-sm-8">
                                                <div class="form-control" id="phone" name="phone" readonly style="color: black; background-color: #ffffff; pointer-events: none;" >
                                                    {{ user_pro.phone }}</div>
                                                </div>
                                            </div>
                                          
                                            <div class="form-group row">
                                                <label for="email" class="col-sm-4 col-form-label">Email:</label>
                                                <div class="col-sm-8">
                                                <div  class="form-control" id="email" name="email" readonly style="color: black; background-color: #ffffff; pointer-events: none;" >
                                                    {{ user.email }}</div>
                                                </div>
                                            </div>
                                            <br>
                                        </div>
                                    </td>
                                </tr>
                        </table>
                    </div>
                    <div class="flex-w flex-sb-m bor15 p-t-18 p-b-15 p-lr-40 p-lr-15-sm">
                        <a href="{% url 'shop_app:shop' %}" class="flex-c-m stext-101 cl2 size-119 bg8 bor13 p-lr-15 trans-04 pointer m-tb-10" >
                              Continue Shopping
                          </a>
                          <a href="{% url 'coupon_app:coupon' %}" class="flex-c-m stext-101 cl2 size-119 bg8 bor13 p-lr-15 trans-04 pointer m-tb-10" >
                            Proceed to Coupon
                        </a>
                          
                      </div>
                    
                </div>
            </div>

            <div class="col-sm-10 col-lg-7 col-xl-5 m-lr-auto m-b-50">
                <div class="bor10 p-lr-40 p-t-30 p-b-40 m-l-63 m-r-40 m-lr-0-xl p-lr-15-sm">
                    
                   

                    <a href="{% url 'account:edit_profile' %}" class="flex-c-m stext-101 cl0 size-111 bg3 bor14 p-lr-15 trans-04 pointer btn-sm" style="text-decoration: none; color: white; ">
                        Edit Profile
                    </a>
                    
                    <br>
                    <a href="{% url 'account:change_password' %}" class="flex-c-m stext-101 cl0 size-111 bg3 bor14 p-lr-15 trans-04 pointer btn-sm" style="text-decoration: none; color: white;">
                        Change Password
                    </a>
                    <br>
                    <a href="{% url 'user_app:user_order' %}" class="flex-c-m stext-101 cl0 size-111 bg3 bor14 p-lr-15 trans-04 pointer btn-sm" style="text-decoration: none; color: white;">
                        My Orders
                    </a>
                    <br>
                    <a href="{% url 'account:user_logout' %}" class="flex-c-m stext-101 cl0 size-111 bg3 bor14 p-lr-15 trans-04 pointer btn-sm" style="text-decoration: none; color: white;">
                        Log out
                    </a>
                    
                </div>
            </div>
        </div>
    </div>
</form>
     


 <script>
    document.addEventListener('DOMContentLoaded', function() {
        
      {% if messages %}
      console.log("halooooooooooooo")
        var message = "{{ messages }}";
        Swal.fire({
            title: "Congrats!",
            text: "You have recieved a coupon.",
            imageUrl: "https://i.pinimg.com/564x/51/5a/05/515a05967e11ca1929a96d3c60855061.jpg",
            imageWidth: 200,
            imageHeight: 200,
            imageAlt: "Custom image"
          });
      {% endif %}
    });
  </script>


{% endblock %}
{% include 'footer.html' %}

accounts/templates/reset_password_email.html
{% autoescape off %}

Hi {{user.first_name }},

As requested, please click on the link below to reset your password:
http://{{domain}}{% url 'account:reset_password_validate' uidb64=uid token=token %}

{% endautoescape %}